# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod properties
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
neoforge_version=26.2.0.50-beta
neoforge_version_range=[26.2.0.50-beta,)
mod_version=12.0.0

# Dependency properties
diag_blocks_version=21.11.1
puzzles_lib_coord=7357960
diagonal_fences_coord=7387915
diagonal_windows_coord=7387912

buildinggadgets_coord=3829297
buildinggadgets_version=3.14.0

jei_mc_version=26.2
jei_version=30.18.0.144

create_mc_version=1.21.1
create_version=6.0.2
create_build_number=32
flywheel_version=1.0.1-11
ponder_version=1.0.44
registrate_version=MC1.21-1.3.0+62

moonlight_coord=6285008
amendments_coord=6258329
amendments_version=1.21-1.2.24

ae2_version=26.1.6-alpha

jade_version=26.2.10
jade_coord=8755115
jade_sources_coord=8755116

atlasviewer_coord=8618518
atlasviewer_version=17.1.0

searchables_mc_version=26.2
searchables_version=1.0.1

additionalplacements_coord=7958573
additionalplacements_version=3.0.1.1
